name: dev-env
id: 'ari:cloud:compass:89436501-45fd-498f-9c7c-b0db10b968cb:component/d819e7ce-7ec1-48ae-b718-cb3459fc6e06/407347d1-1a05-4a0c-b355-17f649d8b88d'
slug: dev-env
description: >-
  This is a collection of shared files, configs, and nix-flakes for use in development. This is used by a large number of systems and should be
  treated as critical to those.
configVersion: 1
typeId: APPLICATION
ownerId: 'ari:cloud:identity::team/a02a5231-1c88-4ca9-9e4b-6b818f80865d'
fields:
  lifecycle: Active
  tier: 1
  isMonorepoProject: false
links:
  - name: null
    type: REPOSITORY
    url: 'https://github.com/devnw/dev-env'
  - name: ''
    type: PROJECT
    url: 'https://devnw.atlassian.net/browse/SPY'
relationships: {}
labels:
  - 'source:github'
  - 'source:nix'
  - 'source:yml'
  - 'source:yaml'
  - 'source:flake'
  - 'source:makefile'
  - 'source:pre-commit'
  - 'source:shell'
  - 'source:script'
  - synced-with-jsm
customFields: null
# Learn more about formatting compass.yml:
# https://go.atlassian.com/compass-yml-format
