name: dev-env
id: 'ari:cloud:compass:89436501-45fd-498f-9c7c-b0db10b968cb:component/d819e7ce-7ec1-48ae-b718-cb3459fc6e06/d6984046-387b-4a95-a16c-d36a0e96769a'
slug: oss-devnw-dev-env
description: >-
  This is a collection of shared files, configs, and nix-flakes for use in
  development. This is used by a large number of systems and should be
  treated as critical to those.
ownerId: 'ari:cloud:identity::team/ed895264-a5df-48d6-9aa2-f44fe1686317'
fields:
  tier: 2
  lifecycle: Active
  isMonorepoProject: false
links:
  - name: null
    type: REPOSITORY
    url: 'https://github.com/devnw/dev-env'
  - name: ''
    type: PROJECT
    url: 'https://devnw.atlassian.net/browse/DEV'
  - name: Slack
    type: CHAT_CHANNEL
    url: 'https://codeprosorg.slack.com/archives/C09MCUT88MS'
relationships: {}
labels:
  - 'source:github'
  - 'source:nix'
  - 'source:yml'
  - 'source:yaml'
  - 'source:flake'
  - 'source:makefile'
  - 'source:pre-commit'
  - 'source:shell'
  - 'source:script'
  - synced-with-jsm
customFields: null
# Learn more about formatting compass.yml:
# https://go.atlassian.com/compass-yml-format
