exclude: '^$'
fail_fast: true
repos:
  # License header enforcement
  - repo: local
    hooks:
      - id: license
        name: add license headers
        entry: bash -lc 'license'
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        exclude: ^templates/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
